#!/usr/bin/bash

cd ~/proj/efj/toolkit
source venv/bin/activate

pycodestyle efjtk
if [ $? -ne "0" ]
then
    exit 1
fi

mypy efjtk
if [ $? -ne "0" ]
then
    exit 2
fi

pyflakes efjtk
if [ $? -ne "0" ]
then
    exit 3
fi

cd tests
python -m unittest
if [ $? -ne "0" ]
then
    exit 4
fi
